import { Inter, Outfit } from "next/font/google";
import "./globals.css";

import { Toaster } from "@/components/ui/sonner";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "A-Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang='en'>
        <body className={outfit.className}>
          {/* <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn> */}
          <Toaster />
          {children}
        </body>
      </html>
  );
}

